#!/bin/sh
#java -DJAEGER_AGENT_HOST=192.168.1.113 -cp ./otdockerexample.jar:./dependency/* lesson05.solution.Formatter sergey 99f9848e8fd25a9e:99f9848e8fd25a9e:0:1
java -DJAEGER_AGENT_HOST=192.168.1.113 -cp ./otdockerexample.jar:./dependency/* lesson05.solution.Formatter
